plugins {
    id 'java-library'
}

dependencies {
    implementation 'org.springframework:spring-web'
    implementation 'com.fasterxml.jackson.core:jackson-annotations'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
