---
# GitHub Labels - 이슈 템플릿에 맞춘 최소 구성
# 최상위는 배열이어야 합니다.

- name: init
  color: "5319e7"
  description: "🚀 초기 세팅/프로젝트 인입"

- name: feat
  color: "0e8a16"
  description: "✨ 기능 추가"

- name: fix
  color: "d73a4a"
  description: "🐛 버그 수정"

- name: chore
  color: "fbca04"
  description: "⚙️ 빌드/배포/유지보수 작업"
