plugins {
    id 'java-library'
}

dependencies {
    implementation project(':ssd-domain')
    implementation project(':ssd-common')
    implementation project(':ssd-external')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'io.github.openfeign:feign-core:13.6'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
