plugins {
    id 'java-library'
}

dependencies {
    implementation project(':ssd-common')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    api 'io.swagger.core.v3:swagger-annotations-jakarta:2.2.41'
    implementation platform('software.amazon.awssdk:bom:2.32.20')
    implementation 'software.amazon.awssdk:s3'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
